version: '3.7'

services:
  client:
    image: node:12.7.0-buster
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - .:/projects
      - v-sync-client:/projects/client
      - v-client-yarn:/usr/local/share/.cache/yarn
    working_dir: /projects/client
    command: /bin/sh
    tty: true

  php:
    build: ./docker/php
    volumes:
      - ./server:/var/www

  nginx:
    image: nginx
    ports:
      - 8000:8000
    volumes:
      - ./server:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    build:
      context: ./docker/db/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog123
      TZ: 'Asia/Tokyo'
    volumes:
      # - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  v-sync-client:
    external: true
  v-client-yarn:
